In [16]:
import numpy as np
import pandas as pd
import seaborn as sns

def get_file_using_PublicURL(public_url):
  file_id_url = public_url.split('/')[-2]
  return 'https://drive.google.com/uc?id=' + file_id_url

# ACCES DATA ONLINE
try:
    dataset = pd.read_csv( 'WA_Fn-UseC_-Telco-Customer-Churn.csv', index_col = 0 )
    churn_telco = pd.read_csv( 'tel_churn.csv', index_col = 0 )
    first_telco = pd.read_csv( 'first_telc.csv', index_col = 0 )    
except:
    dataset = pd.read_csv( get_file_using_PublicURL('https://drive.google.com/file/d/18LJnC1W2HUaHFD7WCP8tOm56Kk9FwMdS/view?usp=drive_link'), index_col = 0 )
    churn_telco = pd.read_csv( get_file_using_PublicURL('https://drive.google.com/file/d/1FYHXc-jV5Jl6s2ee6voRc4i_ouMcsxtX/view?usp=drive_link'), index_col = 0 )
    first_telco = pd.read_csv( get_file_using_PublicURL('https://drive.google.com/file/d/1CCY55fjvKFSEe_6aHrm0e_DDJftrXmPa/view?usp=drive_link'), index_col = 0 )

## TELCO CUSTOMER

In [50]:
dataset.info()
print('\nCount NA rows\n',dataset.isna().sum())
print('\nCount duplicated rows\n',dataset.duplicated().sum())
# dataset[(dataset.duplicated())]
dataset.drop_duplicates(inplace=True)
print('\nAfter removing the duplicated rows\n')

# dataset.describe().transpose()
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7021 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7021 non-null   object
 1   SeniorCitizen     7021 non-null   int64
 2   Partner           7021 non-null   object
 3   Dependents        7021 non-null   object
 4   tenure            7021 non-null   int64
 5   PhoneService      7021 non-null   object
 6   MultipleLines     7021 non-null   object
 7   InternetService   7021 non-null   object
 8   OnlineSecurity    7021 non-null   object
 9   OnlineBackup      7021 non-null   object
 10  DeviceProtection  7021 non-null   object
 11  TechSupport       7021 non-null   object
 12  StreamingTV       7021 non-null   object
 13  StreamingMovies   7021 non-null   object
 14  Contract          7021 non-null   object
 15  PaperlessBilling  7021 non-null   object
 16  PaymentMethod     7021 non-null   object
 17  MonthlyCharges    7021 non-null   float64
 18  TotalCharges      7021 non-null   object
 19  Churn             7021 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.4+ MB

Count NA rows
 gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Count duplicated rows
 0

After removing the duplicated rows

<class 'pandas.core.frame.DataFrame'>
Index: 7021 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7021 non-null   object
 1   SeniorCitizen     7021 non-null   int64
 2   Partner           7021 non-null   object
 3   Dependents        7021 non-null   object
 4   tenure            7021 non-null   int64
 5   PhoneService      7021 non-null   object
 6   MultipleLines     7021 non-null   object
 7   InternetService   7021 non-null   object
 8   OnlineSecurity    7021 non-null   object
 9   OnlineBackup      7021 non-null   object
 10  DeviceProtection  7021 non-null   object
 11  TechSupport       7021 non-null   object
 12  StreamingTV       7021 non-null   object
 13  StreamingMovies   7021 non-null   object
 14  Contract          7021 non-null   object
 15  PaperlessBilling  7021 non-null   object
 16  PaymentMethod     7021 non-null   object
 17  MonthlyCharges    7021 non-null   float64
 18  TotalCharges      7021 non-null   object
 19  Churn             7021 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [49]:
dataset[ (dataset['TotalCharges']==' ') ]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
customerID,,,,,,,,,,,,,,,,,,,,
4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

Found some people with NA TotalCharges, these rows must be droped

In [72]:
dataset = dataset[(dataset['TotalCharges']!=' ')]
dataset['TotalCharges'] = dataset['TotalCharges'].astype('float64')
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7010 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7010 non-null   object
 1   SeniorCitizen     7010 non-null   int64
 2   Partner           7010 non-null   object
 3   Dependents        7010 non-null   object
 4   tenure            7010 non-null   int64
 5   PhoneService      7010 non-null   object
 6   MultipleLines     7010 non-null   object
 7   InternetService   7010 non-null   object
 8   OnlineSecurity    7010 non-null   object
 9   OnlineBackup      7010 non-null   object
 10  DeviceProtection  7010 non-null   object
 11  TechSupport       7010 non-null   object
 12  StreamingTV       7010 non-null   object
 13  StreamingMovies   7010 non-null   object
 14  Contract          7010 non-null   object
 15  PaperlessBilling  7010 non-null   object
 16  PaymentMethod     7010 non-null   object
 17  MonthlyCharges    7010 non-null   float64
 18  TotalCharges      7010 non-null   float64
 19  Churn             7010 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

In [74]:
for column in [col for col in dataset.columns if col not in ['MonthlyCharges','TotalCharges']]:
    print( '{} : {}\n{}\n'.format(column, dataset[column].dtypes, dataset[column].value_counts()) )

gender : object
Male      3535
Female    3475
Name: gender, dtype: int64

SeniorCitizen : int64
0    5869
1    1141
Name: SeniorCitizen, dtype: int64

Partner : object
No     3617
Yes    3393
Name: Partner, dtype: int64

Dependents : object
No     4911
Yes    2099
Name: Dependents, dtype: int64

tenure : int64
1     591
72    362
2     238
3     200
4     176
     ...
38     59
28     57
39     56
44     51
36     50
Name: tenure, Length: 72, dtype: int64

PhoneService : object
Yes    6330
No      680
Name: PhoneService, dtype: int64

MultipleLines : object
No                  3363
Yes                 2967
No phone service     680
Name: MultipleLines, dtype: int64

InternetService : object
Fiber optic    3090
DSL            2414
No             1506
Name: InternetService, dtype: int64

OnlineSecurity : object
No                     3489
Yes                    2015
No internet service    1506
Name: OnlineSecurity, dtype: int64

OnlineBackup : object
No                     3079
Yes                    2425
No internet service    1506
Name: OnlineBackup, dtype: int64

DeviceProtection : object
No                     3086
Yes                    2418
No internet service    1506
Name: DeviceProtection, dtype: int64

TechSupport : object
No                     3464
Yes                    2040
No internet service    1506
Name: TechSupport, dtype: int64

StreamingTV : object
No                     2801
Yes                    2703
No internet service    1506
Name: StreamingTV, dtype: int64

StreamingMovies : object
No                     2773
Yes                    2731
No internet service    1506
Name: StreamingMovies, dtype: int64

Contract : object
Month-to-month    3853
Two year          1685
One year          1472
Name: Contract, dtype: int64

PaperlessBilling : object
Yes    4158
No     2852
Name: PaperlessBilling, dtype: int64

PaymentMethod : object
Electronic check             2359
Mailed check                 1588
Bank transfer (automatic)    1542
Credit card (automatic)      1521
Name: PaymentMethod, dtype: int64

Churn : object
No     5153
Yes    1857
Name: Churn, dtype: int64

## CHURN TELCO CUSTOMER EXTENDED INFORMATION

In [24]:
churn_telco.info()
churn_telco.describe().transpose()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 51 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   SeniorCitizen                            7032 non-null   int64
 1   MonthlyCharges                           7032 non-null   float64
 2   TotalCharges                             7032 non-null   float64
 3   Churn                                    7032 non-null   int64
 4   gender_Female                            7032 non-null   int64
 5   gender_Male                              7032 non-null   int64
 6   Partner_No                               7032 non-null   int64
 7   Partner_Yes                              7032 non-null   int64
 8   Dependents_No                            7032 non-null   int64
 9   Dependents_Yes                           7032 non-null   int64
 10  PhoneService_No                          7032 non-null   int64
 11  PhoneService_Yes                         7032 non-null   int64
 12  MultipleLines_No                         7032 non-null   int64
 13  MultipleLines_No phone service           7032 non-null   int64
 14  MultipleLines_Yes                        7032 non-null   int64
 15  InternetService_DSL                      7032 non-null   int64
 16  InternetService_Fiber optic              7032 non-null   int64
 17  InternetService_No                       7032 non-null   int64
 18  OnlineSecurity_No                        7032 non-null   int64
 19  OnlineSecurity_No internet service       7032 non-null   int64
 20  OnlineSecurity_Yes                       7032 non-null   int64
 21  OnlineBackup_No                          7032 non-null   int64
 22  OnlineBackup_No internet service         7032 non-null   int64
 23  OnlineBackup_Yes                         7032 non-null   int64
 24  DeviceProtection_No                      7032 non-null   int64
 25  DeviceProtection_No internet service     7032 non-null   int64
 26  DeviceProtection_Yes                     7032 non-null   int64
 27  TechSupport_No                           7032 non-null   int64
 28  TechSupport_No internet service          7032 non-null   int64
 29  TechSupport_Yes                          7032 non-null   int64
 30  StreamingTV_No                           7032 non-null   int64
 31  StreamingTV_No internet service          7032 non-null   int64
 32  StreamingTV_Yes                          7032 non-null   int64
 33  StreamingMovies_No                       7032 non-null   int64
 34  StreamingMovies_No internet service      7032 non-null   int64
 35  StreamingMovies_Yes                      7032 non-null   int64
 36  Contract_Month-to-month                  7032 non-null   int64
 37  Contract_One year                        7032 non-null   int64
 38  Contract_Two year                        7032 non-null   int64
 39  PaperlessBilling_No                      7032 non-null   int64
 40  PaperlessBilling_Yes                     7032 non-null   int64
 41  PaymentMethod_Bank transfer (automatic)  7032 non-null   int64
 42  PaymentMethod_Credit card (automatic)    7032 non-null   int64
 43  PaymentMethod_Electronic check           7032 non-null   int64
 44  PaymentMethod_Mailed check               7032 non-null   int64
 45  tenure_group_1 - 12                      7032 non-null   int64
 46  tenure_group_13 - 24                     7032 non-null   int64
 47  tenure_group_25 - 36                     7032 non-null   int64
 48  tenure_group_37 - 48                     7032 non-null   int64
 49  tenure_group_49 - 60                     7032 non-null   int64
 50  tenure_group_61 - 72                     7032 non-null   int64
dtypes: float64(2), int64(49)
memory usage: 2.8 MB

,count,mean,std,min,25%,50%,75%,max
SeniorCitizen,7032.0,0.162400,0.368844,0.00,0.0000,0.000,0.0000,1.00
MonthlyCharges,7032.0,64.798208,30.085974,18.25,35.5875,70.350,89.8625,118.75
TotalCharges,7032.0,2283.300441,2266.771362,18.80,401.4500,1397.475,3794.7375,8684.80
Churn,7032.0,0.265785,0.441782,0.00,0.0000,0.000,1.0000,1.00
gender_Female,7032.0,0.495307,0.500014,0.00,0.0000,0.000,1.0000,1.00
gender_Male,7032.0,0.504693,0.500014,0.00,0.0000,1.000,1.0000,1.00
Partner_No,7032.0,0.517491,0.499729,0.00,0.0000,1.000,1.0000,1.00
Partner_Yes,7032.0,0.482509,0.499729,0.00,0.0000,0.000,1.0000,1.00
Dependents_No,7032.0,0.701507,0.457629,0.00,0.0000,1.000,1.0000,1.00
Dependents_Yes,7032.0,0.298493,0.457629,0.00,0.0000,0.000,1.0000,1.00
PhoneService_No,7032.0,0.096701,0.295571,0.00,0.0000,0.000,0.0000,1.00
PhoneService_Yes,7032.0,0.903299,0.295571,0.00,1.0000,1.000,1.0000,1.00
MultipleLines_No,7032.0,0.481371,0.499688,0.00,0.0000,0.000,1.0000,1.00
MultipleLines_No phone service,7032.0,0.096701,0.295571,0.00,0.0000,0.000,0.0000,1.00
MultipleLines_Yes,7032.0,0.421928,0.493902,0.00,0.0000,0.000,1.0000,1.00
InternetService_DSL,7032.0,0.343572,0.474934,0.00,0.0000,0.000,1.0000,1.00
InternetService_Fiber optic,7032.0,0.440273,0.496455,0.00,0.0000,0.000,1.0000,1.00
InternetService_No,7032.0,0.216155,0.411650,0.00,0.0000,0.000,0.0000,1.00
OnlineSecurity_No,7032.0,0.497298,0.500028,0.00,0.0000,0.000,1.0000,1.00
OnlineSecurity_No internet service,7032.0,0.216155,0.411650,0.00,0.0000,0.000,0.0000,1.00
OnlineSecurity_Yes,7032.0,0.286547,0.452180,0.00,0.0000,0.000,1.0000,1.00
OnlineBackup_No,7032.0,0.438993,0.496300,0.00,0.0000,0.000,1.0000,1.00
OnlineBackup_No internet service,7032.0,0.216155,0.411650,0.00,0.0000,0.000,0.0000,1.00
OnlineBackup_Yes,7032.0,0.344852,0.475354,0.00,0.0000,0.000,1.0000,1.00
DeviceProtection_No,7032.0,0.439989,0.496421,0.00,0.0000,0.000,1.0000,1.00
DeviceProtection_No internet service,7032.0,0.216155,0.411650,0.00,0.0000,0.000,0.0000,1.00
DeviceProtection_Yes,7032.0,0.343857,0.475028,0.00,0.0000,0.000,1.0000,1.00
TechSupport_No,7032.0,0.493743,0.499996,0.00,0.0000,0.000,1.0000,1.00
TechSupport_No internet service,7032.0,0.216155,0.411650,0.00,0.0000,0.000,0.0000,1.00
TechSupport_Yes,7032.0,0.290102,0.453842,0.00,0.0000,0.000,1.0000,1.00
StreamingTV_No,7032.0,0.399460,0.489822,0.00,0.0000,0.000,1.0000,1.00
StreamingTV_No internet service,7032.0,0.216155,0.411650,0.00,0.0000,0.000,0.0000,1.00
StreamingTV_Yes,7032.0,0.384386,0.486484,0.00,0.0000,0.000,1.0000,1.00
StreamingMovies_No,7032.0,0.395478,0.488988,0.00,0.0000,0.000,1.0000,1.00
StreamingMovies_No internet service,7032.0,0.216155,0.411650,0.00,0.0000,0.000,0.0000,1.00
StreamingMovies_Yes,7032.0,0.388367,0.487414,0.00,0.0000,0.000,1.0000,1.00
Contract_Month-to-month,7032.0,0.551052,0.497422,0.00,0.0000,1.000,1.0000,1.00
Contract_One year,7032.0,0.209329,0.406858,0.00,0.0000,0.000,0.0000,1.00
Contract_Two year,7032.0,0.239619,0.426881,0.00,0.0000,0.000,0.0000,1.00
PaperlessBilling_No,7032.0,0.407281,0.491363,0.00,0.0000,0.000,1.0000,1.00
PaperlessBilling_Yes,7032.0,0.592719,0.491363,0.00,0.0000,1.000,1.0000,1.00
PaymentMethod_Bank transfer (automatic),7032.0,0.219283,0.413790,0.00,0.0000,0.000,0.0000,1.00
PaymentMethod_Credit card (automatic),7032.0,0.216297,0.411748,0.00,0.0000,0.000,0.0000,1.00
PaymentMethod_Electronic check,7032.0,0.336320,0.472483,0.00,0.0000,0.000,1.0000,1.00
PaymentMethod_Mailed check,7032.0,0.228100,0.419637,0.00,0.0000,0.000,0.0000,1.00
tenure_group_1 - 12,7032.0,0.309300,0.462238,0.00,0.0000,0.000,1.0000,1.00
tenure_group_13 - 24,7032.0,0.145620,0.352750,0.00,0.0000,0.000,0.0000,1.00
tenure_group_25 - 36,7032.0,0.118316,0.323005,0.00,0.0000,0.000,0.0000,1.00
tenure_group_37 - 48,7032.0,0.108362,0.310859,0.00,0.0000,0.000,0.0000,1.00
tenure_group_49 - 60,7032.0,0.118316,0.323005,0.00,0.0000,0.000,0.0000,1.00
tenure_group_61 - 72,7032.0,0.200085,0.400092,0.00,0.0000,0.000,0.0000,1.00

In [76]:
churn_telco.sample(30)

,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
6707,1,25.70,1937.40,0,1,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,1
6649,0,19.85,138.85,0,0,1,0,1,0,1,...,0,1,0,0,1,0,0,0,0,0
5902,0,50.85,466.60,0,1,0,0,1,1,0,...,0,0,0,1,1,0,0,0,0,0
2661,0,47.40,3177.25,0,1,0,1,0,1,0,...,0,0,0,1,0,0,0,0,0,1
2365,1,93.90,1743.90,0,0,1,1,0,1,0,...,1,0,0,0,0,1,0,0,0,0
4442,0,78.50,242.05,1,0,1,1,0,1,0,...,0,0,1,0,1,0,0,0,0,0
2668,0,19.75,19.75,1,0,1,1,0,0,1,...,0,0,0,1,1,0,0,0,0,0
5328,0,66.05,3462.10,0,1,0,0,1,1,0,...,0,1,0,0,0,0,0,0,1,0
2445,0,74.40,1972.35,0,1,0,0,1,0,1,...,0,0,0,1,0,0,1,0,0,0
4518,1,81.25,585.95,1,0,1,1,0,1,0,...,0,0,1,0,1,0,0,0,0,0
2875,0,85.10,1873.70,1,0,1,0,1,1,0,...,0,0,1,0,0,1,0,0,0,0
3648,0,90.15,4554.85,0,1,0,0,1,0,1,...,0,0,1,0,0,0,0,0,1,0
4943,0,84.40,5969.30,0,1,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,1
4722,0,70.15,4224.70,0,1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,1,0
6784,0,24.70,465.85,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,0,0,0
2156,0,80.55,184.10,1,1,0,1,0,1,0,...,0,0,1,0,1,0,0,0,0,0
3474,1,85.75,5688.45,0,0,1,0,1,0,1,...,0,0,1,0,0,0,0,0,0,1
1033,0,23.65,1416.75,0,1,0,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1
6331,0,40.30,1794.80,0,0,1,0,1,0,1,...,0,0,1,0,0,0,0,1,0,0
1016,0,80.10,5585.40,0,0,1,0,1,1,0,...,0,0,0,1,0,0,0,0,0,1
5717,1,56.55,3952.65,0,0,1,0,1,1,0,...,0,1,0,0,0,0,0,0,0,1
3464,0,83.85,2674.15,0,1,0,0,1,1,0,...,1,0,0,0,0,0,1,0,0,0
924,1,81.70,1820.90,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,0,0,0
372,0,35.75,830.80,0,0,1,1,0,0,1,...,0,0,0,1,0,1,0,0,0,0
6749,0,79.40,5528.90,0,0,1,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1
2380,0,103.75,5969.95,0,0,1,0,1,0,1,...,1,0,0,0,0,0,0,0,1,0
3569,0,19.95,310.60,0,0,1,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
5197,0,110.15,7998.80,0,1,0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,1
4683,0,94.10,2322.85,0,0,1,1,0,1,0,...,0,0,1,0,0,1,0,0,0,0
4836,0,78.35,1837.90,0,1,0,1,0,1,0,...,1,0,0,0,0,0,1,0,0,0

In [81]:
for column in churn_telco.columns:
    print( '{} : {}\n{}\n'.format(column, churn_telco[column].dtypes, churn_telco[column].value_counts()) )

SeniorCitizen : int64
0    5890
1    1142
Name: SeniorCitizen, dtype: int64

MonthlyCharges : float64
20.05     61
19.90     44
19.95     44
19.85     44
19.65     43
          ..
23.65      1
114.70     1
43.65      1
87.80      1
78.70      1
Name: MonthlyCharges, Length: 1584, dtype: int64

TotalCharges : float64
20.20      11
19.75       9
20.05       8
19.90       8
19.65       8
           ..
6849.40     1
692.35      1
130.15      1
3211.90     1
6844.50     1
Name: TotalCharges, Length: 6530, dtype: int64

Churn : int64
0    5163
1    1869
Name: Churn, dtype: int64

gender_Female : int64
0    3549
1    3483
Name: gender_Female, dtype: int64

gender_Male : int64
1    3549
0    3483
Name: gender_Male, dtype: int64

Partner_No : int64
1    3639
0    3393
Name: Partner_No, dtype: int64

Partner_Yes : int64
0    3639
1    3393
Name: Partner_Yes, dtype: int64

Dependents_No : int64
1    4933
0    2099
Name: Dependents_No, dtype: int64

Dependents_Yes : int64
0    4933
1    2099
Name: Dependents_Yes, dtype: int64

PhoneService_No : int64
0    6352
1     680
Name: PhoneService_No, dtype: int64

PhoneService_Yes : int64
1    6352
0     680
Name: PhoneService_Yes, dtype: int64

MultipleLines_No : int64
0    3647
1    3385
Name: MultipleLines_No, dtype: int64

MultipleLines_No phone service : int64
0    6352
1     680
Name: MultipleLines_No phone service, dtype: int64

MultipleLines_Yes : int64
0    4065
1    2967
Name: MultipleLines_Yes, dtype: int64

InternetService_DSL : int64
0    4616
1    2416
Name: InternetService_DSL, dtype: int64

InternetService_Fiber optic : int64
0    3936
1    3096
Name: InternetService_Fiber optic, dtype: int64

InternetService_No : int64
0    5512
1    1520
Name: InternetService_No, dtype: int64

OnlineSecurity_No : int64
0    3535
1    3497
Name: OnlineSecurity_No, dtype: int64

OnlineSecurity_No internet service : int64
0    5512
1    1520
Name: OnlineSecurity_No internet service, dtype: int64

OnlineSecurity_Yes : int64
0    5017
1    2015
Name: OnlineSecurity_Yes, dtype: int64

OnlineBackup_No : int64
0    3945
1    3087
Name: OnlineBackup_No, dtype: int64

OnlineBackup_No internet service : int64
0    5512
1    1520
Name: OnlineBackup_No internet service, dtype: int64

OnlineBackup_Yes : int64
0    4607
1    2425
Name: OnlineBackup_Yes, dtype: int64

DeviceProtection_No : int64
0    3938
1    3094
Name: DeviceProtection_No, dtype: int64

DeviceProtection_No internet service : int64
0    5512
1    1520
Name: DeviceProtection_No internet service, dtype: int64

DeviceProtection_Yes : int64
0    4614
1    2418
Name: DeviceProtection_Yes, dtype: int64

TechSupport_No : int64
0    3560
1    3472
Name: TechSupport_No, dtype: int64

TechSupport_No internet service : int64
0    5512
1    1520
Name: TechSupport_No internet service, dtype: int64

TechSupport_Yes : int64
0    4992
1    2040
Name: TechSupport_Yes, dtype: int64

StreamingTV_No : int64
0    4223
1    2809
Name: StreamingTV_No, dtype: int64

StreamingTV_No internet service : int64
0    5512
1    1520
Name: StreamingTV_No internet service, dtype: int64

StreamingTV_Yes : int64
0    4329
1    2703
Name: StreamingTV_Yes, dtype: int64

StreamingMovies_No : int64
0    4251
1    2781
Name: StreamingMovies_No, dtype: int64

StreamingMovies_No internet service : int64
0    5512
1    1520
Name: StreamingMovies_No internet service, dtype: int64

StreamingMovies_Yes : int64
0    4301
1    2731
Name: StreamingMovies_Yes, dtype: int64

Contract_Month-to-month : int64
1    3875
0    3157
Name: Contract_Month-to-month, dtype: int64

Contract_One year : int64
0    5560
1    1472
Name: Contract_One year, dtype: int64

Contract_Two year : int64
0    5347
1    1685
Name: Contract_Two year, dtype: int64

PaperlessBilling_No : int64
0    4168
1    2864
Name: PaperlessBilling_No, dtype: int64

PaperlessBilling_Yes : int64
1    4168
0    2864
Name: PaperlessBilling_Yes, dtype: int64

PaymentMethod_Bank transfer (automatic) : int64
0    5490
1    1542
Name: PaymentMethod_Bank transfer (automatic), dtype: int64

PaymentMethod_Credit card (automatic) : int64
0    5511
1    1521
Name: PaymentMethod_Credit card (automatic), dtype: int64

PaymentMethod_Electronic check : int64
0    4667
1    2365
Name: PaymentMethod_Electronic check, dtype: int64

PaymentMethod_Mailed check : int64
0    5428
1    1604
Name: PaymentMethod_Mailed check, dtype: int64

tenure_group_1 - 12 : int64
0    4857
1    2175
Name: tenure_group_1 - 12, dtype: int64

tenure_group_13 - 24 : int64
0    6008
1    1024
Name: tenure_group_13 - 24, dtype: int64

tenure_group_25 - 36 : int64
0    6200
1     832
Name: tenure_group_25 - 36, dtype: int64

tenure_group_37 - 48 : int64
0    6270
1     762
Name: tenure_group_37 - 48, dtype: int64

tenure_group_49 - 60 : int64
0    6200
1     832
Name: tenure_group_49 - 60, dtype: int64

tenure_group_61 - 72 : int64
0    5625
1    1407
Name: tenure_group_61 - 72, dtype: int64

## First TELCO

In [20]:
first_telco.info()
first_telco.describe().transpose()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 75 entries, 0 to 20
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            75 non-null     object
 1   SeniorCitizen     75 non-null     int64
 2   Partner           75 non-null     object
 3   Dependents        75 non-null     object
 4   tenure            75 non-null     int64
 5   PhoneService      75 non-null     object
 6   MultipleLines     75 non-null     object
 7   InternetService   75 non-null     object
 8   OnlineSecurity    75 non-null     object
 9   OnlineBackup      75 non-null     object
 10  DeviceProtection  75 non-null     object
 11  TechSupport       75 non-null     object
 12  StreamingTV       75 non-null     object
 13  StreamingMovies   75 non-null     object
 14  Contract          75 non-null     object
 15  PaperlessBilling  75 non-null     object
 16  PaymentMethod     75 non-null     object
 17  MonthlyCharges    75 non-null     float64
 18  TotalCharges      75 non-null     object
dtypes: float64(1), int64(2), object(16)
memory usage: 11.7+ KB

                count       mean        std    min   25%   50%   75%     max
SeniorCitizen    75.0   0.106667   0.310768   0.00   0.0   0.0   0.0    1.00
tenure           75.0  35.080000  21.663745   0.00  16.5  35.0  53.5   72.00
MonthlyCharges   75.0  70.251333  30.601572  18.95  47.2  75.0  97.3  113.25

In [21]:
first_telco.head(50)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
6,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4
11,Male,0,No,No,16,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),18.95,326.8
5,Female,0,No,No,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
7,Female,0,No,No,10,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9
8,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05
9,Male,0,No,Yes,62,Yes,No,DSL,Yes,Yes,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95
10,Male,0,Yes,Yes,13,Yes,No,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Mailed check,49.95,587.45
12,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,One year,No,Credit card (automatic),100.35,5681.1
13,Male,0,No,No,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3
14,Male,0,No,No,25,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,105.50,2686.05
15,Female,0,Yes,Yes,69,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),113.25,7895.15
16,Female,0,No,No,52,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,20.65,1022.95
17,Male,0,No,Yes,71,Yes,Yes,Fiber optic,Yes,No,Yes,No,Yes,Yes,Two year,No,Bank transfer (automatic),106.70,7382.25
19,Female,0,No,No,21,Yes,No,Fiber optic,No,Yes,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,90.05,1862.9
21,Male,0,Yes,No,12,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Bank transfer (automatic),19.80,202.25
25,Female,0,No,No,30,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.30,1530.6
26,Male,0,Yes,Yes,47,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.35,4749.15
28,Male,0,Yes,No,72,Yes,Yes,DSL,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),90.25,6369.45
29,Female,0,No,Yes,17,Yes,No,DSL,No,No,No,No,Yes,Yes,Month-to-month,Yes,Mailed check,64.70,1093.1
32,Female,0,Yes,Yes,27,Yes,No,DSL,Yes,Yes,Yes,Yes,No,No,One year,No,Mailed check,66.15,1874.45
36,Male,0,No,No,5,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,316.9
37,Female,0,No,No,46,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Credit card (automatic),74.80,3548.3
39,Female,0,No,No,11,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),97.85,1105.4
41,Female,0,Yes,Yes,70,Yes,Yes,DSL,Yes,Yes,No,No,Yes,No,Two year,Yes,Credit card (automatic),69.20,4872.35
43,Female,0,No,No,63,Yes,Yes,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,Yes,Credit card (automatic),79.85,4861.45
50,Female,1,No,No,43,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,No,Month-to-month,Yes,Electronic check,90.25,3838.75
51,Female,0,No,No,15,Yes,No,Fiber optic,Yes,Yes,No,No,Yes,Yes,Month-to-month,Yes,Credit card (automatic),99.10,1426.4
54,Female,1,Yes,Yes,60,Yes,No,DSL,Yes,Yes,Yes,Yes,No,Yes,One year,Yes,Credit card (automatic),74.85,4456.35
55,Male,1,No,No,18,Yes,Yes,Fiber optic,No,No,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,95.45,1752.55
57,Male,1,Yes,Yes,66,Yes,Yes,Fiber optic,No,Yes,Yes,Yes,Yes,Yes,One year,Yes,Electronic check,108.45,7076.35
64,Female,0,No,No,9,Yes,Yes,Fiber optic,No,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,94.40,857.25
65,Female,0,No,No,3,Yes,No,DSL,No,Yes,No,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,75.30,244.1
67,Female,0,No,No,31,Yes,No,DSL,No,Yes,Yes,Yes,Yes,Yes,Two year,No,Mailed check,79.20,2497.2
68,Female,0,Yes,Yes,50,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),20.15,930.9
72,Male,1,Yes,Yes,64,Yes,Yes,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),111.60,7099
75,Female,1,No,No,56,Yes,Yes,Fiber optic,Yes,Yes,Yes,No,Yes,Yes,One year,No,Electronic check,110.50,6139.5
82,Female,0,Yes,No,7,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Bank transfer (automatic),75.15,496.9
83,Female,0,No,No,42,Yes,No,Fiber optic,No,Yes,Yes,Yes,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.80,4327.5
86,Female,0,Yes,No,35,Yes,No,DSL,Yes,No,No,No,Yes,No,One year,Yes,Bank transfer (automatic),62.15,2215.45
87,Female,0,Yes,Yes,48,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),20.65,1057
89,Male,0,Yes,No,29,No,No phone service,DSL,No,No,No,No,Yes,No,Month-to-month,No,Mailed check,33.75,1009.25
93,Female,0,No,No,65,Yes,Yes,Fiber optic,Yes,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Credit card (automatic),111.05,7107
102,Male,0,No,No,38,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,No,One year,No,Bank transfer (automatic),95.00,3605.6
104,Male,0,Yes,No,68,Yes,Yes,Fiber optic,No,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),110.00,7611.85
107,Female,0,No,No,32,No,No phone service,DSL,Yes,No,No,No,No,No,One year,No,Mailed check,30.15,927.65

In [22]:
first_telco.index.unique().sort_values(ascending=True)

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
             13,  14,  15,  16,  17,  19,  20,  21,  25,  26,  28,  29,  32,
             36,  37,  39,  41,  43,  50,  51,  54,  55,  57,  64,  65,  67,
             68,  72,  75,  82,  83,  86,  87,  89,  93, 102, 104, 107, 110,
            113, 116, 118, 121, 124, 125, 132, 136, 138, 142, 155, 161, 163,
            189, 194, 196, 204, 208, 230, 250, 435, 488, 546],
           dtype='int64')

# Features Encoding